version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cpvault-postgres
    restart: always
    environment:
      POSTGRES_DB: cpvault_db
      POSTGRES_USER: cpvault_user
      POSTGRES_PASSWORD: cpvault_pass
    ports:
      - "5432:5432"
    volumes:
      - cpvault_data:/var/lib/postgresql/data

volumes:
  cpvault_data:
